calculate_all_zones:
  fields:
    delete_weather_data:
        required: false
        example: false
        default: true
        selector:
          boolean: {}
calculate_zone:
  target:
    entity:
      domain: sensor
  fields:
    delete_weather_data:
        required: false
        example: false
        default: true
        selector:
          boolean: {}
update_all_zones:
update_zone:
  target:
    entity:
      domain: sensor
set_bucket:
  target:
    entity:
      domain: sensor
  fields:
    new_bucket_value:
      required: true
      example: -10
      default: 0
set_all_buckets:
  fields:
    new_bucket_value:
      required: true
      example: -10
      default: 0
reset_bucket:
  target:
    entity:
      domain: sensor
reset_all_buckets:
clear_all_weather_data:
set_all_multipliers:
  fields:
    new_multiplier_value:
      required: true
      example: 1.0
      default: 1.0
set_multiplier:
  target:
    entity:
      domain: sensor
  fields:
    new_multiplier_value:
      required: true
      example: 1.0
      default: 1.0
set_zone:
  target:
    entity:
      domain: sensor
  fields:
    new_bucket_value:
      required: false
      example: -10
      default: 0
    new_multiplier_value:
      required: false
      example: 1.0
      default: 1.0
    new_duration_value:
      required: false
      example: 10
      default: 0
    new_state_value:
      required: false
      example: "automatic"
      default: "automatic"
    new_throughput_value:
      required: false
      example: 50
      default: 50
clear_all_weather_data:
  name: Clear all weather data
  description: Clear all collected weather data from all mappings.
generate_watering_calendar:
  name: Generate watering calendar
  description: Generate a 12-month watering calendar for irrigation zones based on representative climate data.
  fields:
    zone_id:
      name: Zone ID
      description: Optional zone ID to generate calendar for. If not provided, generates for all zones.
      required: false
      example: "1"
      selector:
        text:
