calculate_all_zones:
calculate_zone:
  fields:
    entity:
      domain: sensor
update_all_zones:
update_zone:
  fields:
    entity:
      domain: sensor
set_bucket:
  fields:
    entity:
      domain: sensor
    new_bucket_value:
      required: true
      example: -10
      default: 0
set_all_buckets:
  fields:
    new_bucket_value:
      required: true
      example: -10
      default: 0
reset_bucket:
  fields:
    entity:
      domain: sensor
reset_all_buckets:
clear_all_weather_data: