blueprint:
  name: Irrigation Unlimited adjust watering time for a single zone.
  description: Adjust watering times based on smart irrigation calculations.
  domain: automation
  input:
    irrigation_zone:
      name: Irrigation Zone
      description: Zone to irrigate
      selector:
        entity:
          filter:
            - device_class: duration

    unlimited_zone:
      name: Unlimited Zone
      description: Unlimited zone to irrigate
      selector:
        entity:
          filter:
            - domain: binary_sensor

    time_on:
      name: Time to turn on
      selector:
        time:
      default: "23:30:00"

variables:
  duration: !input irrigation_zone

alias: Smart Irrigation adjustment

trigger:
  platform: time
  at: !input time_on

condition:
  - condition: template
    value_template: "{{ (states('duration') | float(-1)) >= 0 }}"

action:
  - service: irrigation_unlimited.adjust_time
    data:
      actual: "{{ timedelta(seconds=states('duration') | int(0)) }}"
      # 1. Adjust a single zone.
      entity_id: !input unlimited_zone

mode: single
