blueprint:
  name: Irrigation Unlimited adjust watering time.
  description: Adjust watering times based on smart irrigation calculations.
  domain: automation
  input:
    irrigation_zone:
      name: Irrigation Zone
      description: Zone to irrigate
      selector:
        entity:
          filter:
            - device_class: duration

    time_on:
      name: Time to turn on
      selector:
        time:
      default: "23:30:00"

variables:
  duration: !input irrigation_zone

alias: Smart Irrigation adjustment

trigger:
  platform: time
  at: !input time_on

condition:
  - condition: template
    value_template: "{{ (states('duration') | float(-1)) >= 0 }}"

action:
  - service: irrigation_unlimited.adjust_time
    data:
      actual: "{{ timedelta(seconds=states('duration') | int(0)) }}"
      # -------------------------------------------------------------------
      # Please see documentation regarding the adjust_time service call.
      # Choose an option below. Comment out/delete as needed. This will NOT work as is.
      # 1. Adjust a single zone. Change the zone as required
      # entity_id: binary_sensor.irrigation_unlimited_c1_z1
      # 2. Adjust a sequence. Change the sequence_id as required
      # entity_id: binary_sensor.irrigation_unlimited_c1_m
      # sequence_id: 1
      # -------------------------------------------------------------------

mode: single
