description: ""
mode: single
trigger:
  - platform: numeric_state
    entity_id:
      - sensor.smart_irrigation_[zone_name]
    attribute: bucket
    below: -25
  - platform: time
    at: "05:00:00"
condition:
  - condition: or
    conditions:
      - condition: numeric_state
        entity_id: sensor.smart_irrigation_[zone_name]
        below: "-25"
        attribute: bucket
      - condition: and
        conditions:
          - condition: numeric_state
            entity_id: sensor.smart_irrigation_[zone_name]
            above: 0
          - condition: template
            value_template: "{{ now().isoweekday() == 1 }}"
action:
  - service: switch.turn_on
      data: {}
      entity_id: switch.irrigation_tap1
  - delay:
    seconds: '{{states("sensor.[zone_name"])}}'
  - service: switch.turn_off
    data: {}
    entity_id: switch.irrigation_tap1
  - service: smart_irrigation.reset_bucket
    data: {}
    entity_id: sensor.smart_irrigation_[zone_name]
