blueprint:
  name: Simple Scheduler Irrigationt
  description: Irrigation for one zone, called by Simple Scheduler
  domain: script
  input:
    irrigation_switch:
      name: Irrigation Switch
      description: Switch, tap or valve to turn on and off
      selector:
        entity:
          filter:
            - domain: switch

    irrigation_zone:
      name: Irrigation Zone
      description: Zone to irrigate
      selector:
        entity:
          filter:
            - device_class: duration

variables:
  irrigation_time: !input irrigation_zone

alias: Standard Irrigation
description: "Standard irrigation for one Zone"

sequence:
  - condition: numeric_state
    entity_id: !input irrigation_zone
    above: 0

  - service: switch.turn_on
    data: {}
    target:
      entity_id: !input irrigation_switch

  - delay: "{{ states(irrigation_time) }}"

  - service: switch.turn_off
    data: {}
    target:
      entity_id:
        - !input irrigation_switch

  - service: smart_irrigation.reset_bucket
    data: {}
    target:
      entity_id: !input irrigation_zone

mode: single
icon: mdi:sprinkler
