name: CI - Smart Irrigation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Run Tests, Ruff, Pylint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ "3.11" ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-mock pytest-cov pytest-homeassistant-custom-component
          pip install ruff pylint

      - name: Run tests
        run: |
          pytest --cov=custom_components.smart_irrigation --cov-report=xml --disable-warnings

      - name: Run ruff (linting)
        run: |
          ruff custom_components/smart_
