name: Test Smart Irrigation

on:
  push:
  pull_request:
  
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Smart Irrigation
        uses: actions/checkout@v4

      - name: Checkout Home Assistant Core
        uses: actions/checkout@v4
        with:
          repository: home-assistant/core
          path: core

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13-dev'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip uv
          uv venv
          uv pip install -e core  # Editable install of HA
          uv pip install -r requirements.test.txt --system

      - name: Run tests
        run: pytest tests --durations=10
